Repository go-vela/worker, pull requests merged in 2019-12, with the labels that each got.

#28 Update client maps to be sync map
  executor/linux/build.go
  executor/linux/build_test.go
  executor/linux/linux.go
  executor/linux/service.go
  executor/linux/service_test.go
  executor/linux/stage.go
  executor/linux/step.go
  executor/linux/step_test.go
Labels: bug

#29 Upload detached container logs
  executor/linux/service.go
  executor/linux/step.go
Labels: bug

#30 Capture ID from runtime network/volume
  executor/linux/build.go
  runtime/docker/network.go
  runtime/docker/network_test.go
  runtime/docker/volume.go
  runtime/docker/volume_test.go
  runtime/runtime.go
Labels: enhancement

#31 Add ability to inspect Runtime resources
  executor/linux/service.go
  executor/linux/step.go
  runtime/docker/container.go
  runtime/docker/container_test.go
  runtime/docker/network.go
  runtime/docker/volume.go
  runtime/runtime.go
Labels: feature

#33 Add ability to inspect Runtime image
  executor/linux/build.go
  executor/linux/service.go
  executor/linux/step.go
  runtime/docker/container.go
  runtime/docker/container_test.go
  runtime/docker/image.go
  runtime/docker/network.go
  runtime/docker/network_test.go
  runtime/docker/volume.go
  runtime/docker/volume_test.go
  runtime/runtime.go
Labels: feature

#34 Use routes env for queue cluster config
  cmd/server/queue.go
  queue/redis/redis.go
Labels: bug

#36 Add tests for Docker runtime image inspect
  runtime/docker/image_test.go
  runtime/docker/testdata/mock/docker.go
  runtime/docker/testdata/mock/images.go
Labels: enhancement

#37 Add tests for Docker runtime network/volume inspect
  runtime/docker/network_test.go
  runtime/docker/testdata/mock/network.go
  runtime/docker/testdata/mock/volume.go
  runtime/docker/volume_test.go
Labels: enhancement

#35 Add logic to handle init stage/step
  executor/executor.go
  executor/linux/build.go
  executor/linux/stage.go
  executor/linux/stage_test.go
  executor/linux/step.go
Labels: feature

#38 Uptick version for new release
  router/middleware/header_test.go
  version/version.go
Labels: bug

#39 Release v0.2.0-rc2
  go.mod
  go.sum
Labels: enhancement

#40 feat(api): Add executor endpoints
  api/build.go
  api/executor.go
  api/pipeline.go
  api/repo.go
  cmd/server/operate.go
  cmd/server/server.go
  executor/context.go
  executor/executor.go
  executor/linux/build.go
  executor/linux/linux.go
  executor/linux/linux_test.go
  go.mod
  go.sum
  router/build.go
  router/executor.go
  router/middleware/executor.go
  router/middleware/executor/context.go
  router/middleware/executor/context_test.go
  router/middleware/executor/executor.go
  router/middleware/executor/executor_test.go
  router/pipeline.go
  router/repo.go
Labels: feature

#41 Implement kill build endpoint
  api/build.go
  cmd/server/operate.go
  executor/linux/build.go
Labels: feature

#43 chore: update all go mod dependencies
  go.mod
  go.sum
Labels: enhancement

#44 chore: update go-vela dependencies
  go.mod
  go.sum
Labels: enhancement

#45 ci: switch from coveralls to codecov
  .github/README.md
  .github/workflows/test.yml
Labels: enhancement

#46 ci: add explicit configuration for automation
  .golangci.yml
  codecov.yml
Labels: enhancement

#47 refactor: fix linter errors
  api/build.go
  api/executor.go
  api/pipeline.go
  api/repo.go
  cmd/server/executor.go
  cmd/server/queue.go
  cmd/server/runtime.go
  cmd/server/server.go
  executor/linux/build.go
  executor/linux/build_test.go
  executor/linux/linux.go
  executor/linux/secret.go
  executor/linux/secret_test.go
  executor/linux/service.go
  executor/linux/service_test.go
  executor/linux/stage.go
  executor/linux/stage_test.go
  executor/linux/step.go
  executor/linux/step_test.go
  queue/redis/redis.go
  router/build.go
  router/executor.go
  router/middleware/executor/executor_test.go
  router/middleware/header.go
  router/middleware/header_test.go
  router/middleware/logger.go
  router/middleware/logger_test.go
  router/middleware/payload_test.go
  router/middleware/perm/perm_test.go
  router/middleware/token/token.go
  router/middleware/user/user_test.go
  router/pipeline.go
  router/repo.go
  router/router.go
  runtime/docker/container.go
  runtime/docker/container_test.go
  runtime/docker/docker.go
  runtime/docker/network_test.go
  runtime/docker/volume_test.go
Labels: enhancement

#48 chore: update for v0.2.0
  go.mod
  go.sum
Labels: dependencies

#49 ci(linters): update funlen linter settings
  .golangci.yml
Labels: enhancement

#50 fix(ci): disable CGO for publish action
  .github/workflows/publish.yml
Labels: bug
