Repository go-vela/worker, pull requests merged in 2019-11, with the labels that each got.

#6 Split out Actions pipeline per task
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: enhancement

#7 Use goveralls to report test coverage to coveralls
  .github/workflows/test.yml
Labels: enhancement

#8 Add badges to readme
  .github/README.md
Labels: enhancement

#9 Update agent to build no C static links
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: bug

#10 Set proper version for Vela
  router/middleware/header_test.go
  version/version.go
Labels: bug

#11 Upgrade Vela dependencies for login bug
  go.mod
  go.sum
Labels: bug

#12 Refactor to improve Go Report Card
  executor/linux/build.go
  executor/linux/secret_test.go
Labels: enhancement

#13 Update go mod
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: enhancement

#14 Use library/secret.Match for secret injection
  executor/linux/secret.go
  executor/linux/secret_test.go
  router/middleware/header_test.go
  version/version.go
Labels: bug

#15 Adopt official mattn/goveralls integration
  .github/workflows/test.yml
Labels: enhancement

#16 Update go-vela/types for Repo field rename
  go.mod
  go.sum
Labels: bug

#18 Fix(logs): add struct maps for stages/serivces workflows
  executor/linux/build.go
  executor/linux/build_test.go
  executor/linux/linux.go
  executor/linux/service.go
  executor/linux/service_test.go
  executor/linux/stage.go
  executor/linux/step.go
  executor/linux/step_test.go
  go.mod
  go.sum
Labels: bug

#19 Update go-vela dependencies for bug fixes
  go.mod
  go.sum
Labels: bug

#20 Add disclaimer
  .github/README.md
Labels: enhancement

#21 Add the ability to route builds
  cmd/server/main.go
  cmd/server/operate.go
  cmd/server/queue.go
  cmd/server/runtime.go
  cmd/server/server.go
  docker-compose.yml
  go.mod
  go.sum
  queue/queue.go
  queue/redis/pull.go
  queue/redis/redis.go
Labels: feature

#23 Respect YAML pull tag in step configuration
  executor/linux/build.go
  executor/linux/service_test.go
  executor/linux/stage.go
  runtime/docker/container.go
  runtime/docker/container_test.go
Labels: feature

#24 Add worker http endpoints
  api/build.go
  api/executor.go
  api/shutdown.go
  router/build.go
  router/executor.go
  router/router.go
Labels: feature

#25 Add timeout for builds
  cmd/server/main.go
  cmd/server/operate.go
  cmd/server/server.go
Labels: feature

#26 Allow only server to make API calls with secret
  cmd/server/server.go
  go.mod
  go.sum
  router/middleware/perm/doc.go
  router/middleware/perm/perm.go
  router/middleware/perm/perm_test.go
  router/middleware/secret.go
  router/middleware/token/doc.go
  router/middleware/token/token.go
  router/middleware/token/token_test.go
  router/middleware/user/context.go
  router/middleware/user/context_test.go
  router/middleware/user/doc.go
  router/middleware/user/user.go
  router/middleware/user/user_test.go
  router/router.go
Labels: feature

#27 Use setters for Vela resources
  cmd/server/operate.go
  executor/linux/build.go
  executor/linux/service.go
  executor/linux/stage.go
  executor/linux/step.go
Labels: enhancement
