Repository go-vela/worker, pull requests merged in 2020-07, with the labels that each got.

#98 ci: refactor Makefile. improve linter setup. upgrade deps.
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .golangci.yml
  Makefile
  codecov.yml
  go.mod
  go.sum
Labels: dependencies, enhancement

#99 feat(api): add open api (swagger) spec
  api-spec/vela-worker-v0.4.3.json
  api/build.go
  api/executor.go
  api/health.go
  api/metrics.go
  api/pipeline.go
  api/repo.go
  api/shutdown.go
  go.mod
  go.sum
  router/router.go
Labels: feature

#100 fix(queue): update route flag to be correct flag
  cmd/vela-worker/run.go
  docker-compose.yml
Labels: bug

#102 chore: update operator for new executor function
  cmd/vela-worker/exec.go
  docker-compose.yml
  go.mod
  go.sum
Labels: enhancement

#103 chore: update go mod for v0.5.0-rc1
  go.mod
  go.sum
  router/middleware/header_test.go
  version/version.go
Labels: dependencies
