Repository go-vela/worker, pull requests merged in 2020-04, with the labels that each got.

#78 feat: add exec() to run builds
  cmd/vela-worker/client.go
  cmd/vela-worker/exec.go
  cmd/vela-worker/flags.go
  cmd/vela-worker/operate.go
  cmd/vela-worker/run.go
  cmd/vela-worker/server.go
  cmd/vela-worker/start.go
  cmd/vela-worker/validate.go
  cmd/vela-worker/worker.go
  go.mod
  go.sum
Labels: feature

#79 test(middleware): add 100% coverage
  router/middleware/executor/executor_test.go
  router/middleware/executor_test.go
  router/middleware/header_test.go
  router/middleware/perm/perm_test.go
  router/middleware/secret_test.go
Labels: enhancement

#84 chore: update for v0.4.0-rc1
  go.mod
  go.sum
Labels: dependencies

#85 chore: uptick version for release
  router/middleware/header_test.go
  version/version.go
Labels: dependencies

#86 chore: update dependencies for v0.4.0-rc2
  go.mod
  go.sum
Labels: dependencies

#87 chore: update version to v0.4.0-rc3
  go.mod
  go.sum
Labels: dependencies
