Repository go-vela/worker, pull requests merged in 2020-11, with the labels that each got.

#126 refactor: secrets.env -> .env for consistency
  .env.example
  .gitignore
  DOCS.md
  docker-compose.yml
Labels: enhancement

#125 fix: update go-vela/pkg-executor dep for truncated logs
  go.mod
  go.sum
Labels: bug

#127 feat: add option to run with TLS
  cmd/vela-worker/flags.go
  cmd/vela-worker/run.go
  cmd/vela-worker/server.go
  cmd/vela-worker/worker.go
Labels: cancel builds
