Repository go-vela/worker, pull requests merged in 2021-12, with the labels that each got.

#245 fix: local setup with server
  .env.example
  DOCS.md
  docker-compose.yml
Labels: bug

#244 feat(logs): allow setting max log size
  cmd/vela-worker/exec.go
  cmd/vela-worker/run.go
  executor/executor_test.go
  executor/flags.go
  executor/linux/linux.go
  executor/linux/opts.go
  executor/linux/opts_test.go
  executor/linux/service.go
  executor/linux/step.go
  executor/linux/step_test.go
  executor/setup.go
  executor/setup_test.go
  router/middleware/executor/executor_test.go
Labels: feature

#252 chore: update go-vela/server dependency
  go.mod
  go.sum
Labels: dependencies

#246 enhance: use application logger
  cmd/vela-worker/exec.go
  docker-compose.yml
  executor/flags.go
  executor/linux/api.go
  executor/linux/build.go
  executor/linux/linux.go
  executor/linux/opts.go
  executor/linux/secret.go
  executor/linux/service.go
  executor/linux/stage.go
  executor/linux/step.go
  executor/local/opts.go
  executor/setup.go
  runtime/docker/build.go
  runtime/docker/container.go
  runtime/docker/docker.go
  runtime/docker/image.go
  runtime/docker/network.go
  runtime/docker/opts.go
  runtime/docker/volume.go
  runtime/flags.go
  runtime/kubernetes/build.go
  runtime/kubernetes/container.go
  runtime/kubernetes/image.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/network.go
  runtime/kubernetes/opts.go
  runtime/kubernetes/volume.go
  runtime/runtime.go
  runtime/setup.go
Labels: enhancement

#253 fix(docker): pulling images without output
  runtime/docker/image.go
Labels: bug

#255 chore(deps): update go to 1.17
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  go.mod
Labels: dependencies
