Repository go-vela/worker, pull requests merged in 2021-01, with the labels that each got.

#139 chore(deps): upgrade go-vela deps on v0.7.0-rc2
  go.mod
  go.sum
Labels: dependencies

#142 fix: allow workers to retry registering with the server
  cmd/vela-worker/operate.go
  cmd/vela-worker/register.go
Labels: bug

#143 fix: web UI address for server in docker-compose
  docker-compose.yml
Labels: bug

#144 feat: add version information to executor
  cmd/vela-worker/exec.go
  go.mod
  go.sum
Labels: feature
