Repository go-vela/worker, pull requests merged in 2021-02, with the labels that each got.

#149 chore: linter setup and fixes, doc changes
  .github/CONTRIBUTING.md
  .golangci.yml
  api/executor.go
  api/health.go
  api/metrics.go
  cmd/vela-worker/exec.go
  cmd/vela-worker/register.go
  cmd/vela-worker/run.go
  cmd/vela-worker/start.go
  cmd/vela-worker/worker.go
  router/build.go
  router/executor.go
  router/middleware/executor/executor.go
  router/middleware/header.go
  router/middleware/logger_test.go
  router/middleware/payload.go
  router/middleware/perm/doc.go
  router/middleware/perm/perm.go
  router/middleware/token/doc.go
  router/middleware/token/token.go
  router/middleware/user/doc.go
  router/middleware/user/user.go
  router/pipeline.go
  router/repo.go
Labels: enhancement

#150 refactor: use constant for 200 http status code
  router/middleware/header.go
Labels: enhancement

#151 chore: upgrade go-vela deps on v0.7.0
  go.mod
  go.sum
Labels: dependencies

#159 ci(Makefile): remove pull target from up target
  Makefile
Labels: enhancement

#169 fix(executors): set id in returned payload
  api/executor.go
Labels: bug

#170 docs: fix authorization callback url
  DOCS.md
Labels: bug
