Repository go-vela/worker, pull requests merged in 2022-05, with the labels that each got.

#302 enhance(kubernetes): Add podTracker and containerTracker to use k8s API more like a k8s controller
  cmd/vela-worker/exec.go
  executor/linux/build.go
  executor/local/build.go
  runtime/docker/build.go
  runtime/docker/build_test.go
  runtime/engine.go
  runtime/kubernetes/build.go
  runtime/kubernetes/build_test.go
  runtime/kubernetes/container.go
  runtime/kubernetes/container_test.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/kubernetes_test.go
  runtime/kubernetes/pod_tracker.go
  runtime/kubernetes/pod_tracker_test.go
  runtime/kubernetes/volume.go
Labels: enhancement

#332 fix(executor): tests from compiler changes
  executor/linux/build_test.go
  executor/linux/secret_test.go
  executor/linux/stage_test.go
  executor/local/build_test.go
  executor/local/stage_test.go
  go.mod
  go.sum
Labels: bug

#337 bugfix(k8s): Drop TailContainer's logsContext to avoid early cancel
  executor/linux/build.go
  executor/local/build.go
  runtime/kubernetes/container.go
Labels: bug

#338 test: add API mock for Vela Worker
  mock/worker/build.go
  mock/worker/doc.go
  mock/worker/executor.go
  mock/worker/pipeline.go
  mock/worker/repo.go
  mock/worker/server.go
Labels: feature
